### ISSUE TITLE
No need this

### ISSUE THREAD

**Issue by dipto0321** [zenott/Enumerable-Methods#3]
https://github.com/zenott/Enumerable-Methods/blob/49f0d03cd6b0c13df356be6a54dad2d702b75f13/spec/enumerable_spec.rb#L10-L12

I think it should be deleted. Because it will always return you the array. No matter what you did. I don't know why you actually put this test here.

**Comment by dipto0321** [comment]
Same [here](https://github.com/zenott/Enumerable-Methods/blob/49f0d03cd6b0c13df356be6a54dad2d702b75f13/spec/enumerable_spec.rb#L28-L30) 
```
    it 'returns original Array' do
      expect(test_array.my_each_with_index { |n,i| n*i}).to eq(test_array)
    end
```

**Comment by BalintMendli** [comment]
Removed, I just included these to check if the methods work like `each` should, returning the original array, not the modified like with `map`, or `nil` or anything else.
